CREATE TABLE MLP_DEMO_MODEL
   (MODEL_ID NUMBER(10,0) NOT NULL ENABLE,
	FILE_CONTENT BLOB,
	MAX_FEATURE_VALUES VARCHAR2(255 CHAR),
	MIN_FEATURE_VALUES VARCHAR2(255 CHAR),
	MODEL_FILE_NAME VARCHAR2(255 CHAR),
	PRIMARY KEY (MODEL_ID));
